services:
  # ------------------------------------
  # 1. BACKEND (Python / FastAPI)
  # ------------------------------------
  # Desplegamos SOLO el backend autom√°ticamente para asegurar compatibilidad.
  - type: web
    name: gest-backend
    env: docker
    plan: free
    rootDir: ./backend
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
